# Generated by Django 6.0.3 on 2026-04-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_public_consortium_services'),
        ('projects', '0004_task_progress_pct_project_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='is_consortium',
            field=models.BooleanField(default=False, help_text='Project involves a consortium of firms'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public or private project (Public/Privé)'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='services_transversaux',
            field=models.JSONField(blank=True, default=list, help_text="Transversal services: ['BIM', 'PAYSAGE', 'DD', 'CIVIL', 'PATRIMOINE', ...]"),
        ),
        migrations.AddField(
            model_name='project',
            name='is_consortium',
            field=models.BooleanField(default=False, help_text='Project involves a consortium of firms'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public or private project (Public/Privé)'),
        ),
        migrations.AddField(
            model_name='project',
            name='services_transversaux',
            field=models.JSONField(blank=True, default=list, help_text="Transversal services: ['BIM', 'PAYSAGE', 'DD', 'CIVIL', 'PATRIMOINE', ...]"),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='fee_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of construction cost for fee calculation', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='title_on_invoice',
            field=models.CharField(blank=True, default='', help_text='Titre affiché sur les factures (si différent du titre projet)', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='total_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total honoraires HT', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fee_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of construction cost for fee calculation', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_on_invoice',
            field=models.CharField(blank=True, default='', help_text='Titre affiché sur les factures (si différent du titre projet)', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='billing_mode',
            field=models.CharField(choices=[('FORFAIT', 'Forfait (Fixed Price)'), ('HORAIRE', 'Horaire (Hourly)')], default='FORFAIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
