# Generated by Django 6.0.3 on 2026-04-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortiums', '0001_initial'),
        ('projects', '0005_project_public_consortium_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='consortium',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Consortium entity this project belongs to (if is_consortium=True)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='consortiums.consortium'),
        ),
        migrations.AddField(
            model_name='project',
            name='consortium',
            field=models.ForeignKey(blank=True, help_text='Consortium entity this project belongs to (if is_consortium=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='consortiums.consortium'),
        ),
    ]
