# Generated by Django 6.0.3 on 2026-04-21 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_delete_employeeassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="amendment",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this phase belongs to an amendment (avenant) rather than the main project scope.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="projects.amendment",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="amendment",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this task belongs to an amendment (avenant) rather than the main project scope.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.amendment",
            ),
        ),
    ]
