# Generated by Django 6.0.3 on 2026-04-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_phase_amendment_task_amendment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='always_display_in_timesheet',
            field=models.BooleanField(default=False, help_text='Si True, cette tâche apparaît dans la grille hebdomadaire de chaque employé même sans heures saisies (ex: Congés, Administration).'),
        ),
    ]
