# Generated by Django 6.0.3 on 2026-05-29 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_task_always_display_in_timesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, help_text="Membres de l'équipe projet. Permet à un employé de saisir des heures sur le projet même sans planification (allocation).", related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
