# Generated by Django 6.0.3 on 2026-06-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_team_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WBSElement',
        ),
    ]
