# Generated by Django 6.0.3 on 2026-06-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sidebar_config'),
        ('projects', '0012_delete_wbselement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Code court, ex: 1, G, Q', max_length=50)),
                ('name', models.CharField(max_length=255, verbose_name='Nom interne')),
                ('client_facing_label', models.CharField(blank=True, default='', max_length=255)),
                ('phase_type', models.CharField(choices=[('REALIZATION', 'Réalisation'), ('SUPPORT', 'Service de soutien')], default='REALIZATION', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Phase obligatoire sur chaque projet (ex: Gestion de projet).')),
                ('is_active', models.BooleanField(default=True, help_text="Si False, la phase n'est plus instanciée sur les nouveaux projets.")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'projects_standard_phase',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uq_standard_phase_tenant_code')],
            },
        ),
    ]
