# Generated by Django 6.0.3 on 2026-06-06 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sidebar_config'),
        ('projects', '0013_standard_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom interne')),
                ('client_facing_label', models.CharField(blank=True, default='', max_length=255)),
                ('billing_mode', models.CharField(choices=[('FORFAIT', 'Forfait (Fixed Price)'), ('HORAIRE', 'Horaire (Hourly)')], default='FORFAIT', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text="Si False, la tâche n'est plus proposée au démarrage d'un projet.")),
                ('standard_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_tasks', to='projects.standardphase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'projects_standard_task',
                'ordering': ['standard_phase__order', 'order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('standard_phase', 'name'), name='uq_standard_task_phase_name')],
            },
        ),
    ]
