# Generated by Django 6.0.3 on 2026-06-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sidebar_config'),
        ('projects', '0014_standardtask'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='standardtask',
            name='uq_standard_task_phase_name',
        ),
        migrations.AddField(
            model_name='standardtask',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Si défini, cette tâche standard est une SOUS-tâche du modèle.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.standardtask'),
        ),
        migrations.AddConstraint(
            model_name='standardtask',
            constraint=models.UniqueConstraint(fields=('standard_phase', 'parent', 'name'), name='uq_standard_task_phase_parent_name', nulls_distinct=False),
        ),
    ]
