# Generated by Django 6.0.3 on 2026-06-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_tax_scheme_model'),
        ('projects', '0016_support_services_to_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='billing_address',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Adresse (du client) utilisée pour la facturation de CE projet. Vide = adresse de facturation par défaut du client.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.clientaddress', verbose_name='Adresse de facturation du projet'),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='Adresse (du client) utilisée pour la facturation de CE projet. Vide = adresse de facturation par défaut du client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_projects', to='clients.clientaddress', verbose_name='Adresse de facturation du projet'),
        ),
    ]
