# Generated by Django 6.0.3 on 2026-03-18 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertenantassociation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.IntegerField(blank=True, db_index=True, help_text='Null for global roles (ADMIN, FINANCE)', null=True)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('PM', 'Project Manager'), ('PROJECT_DIRECTOR', 'Associé en charge'), ('BU_DIRECTOR', "Directeur d'unité"), ('FINANCE', 'Finance'), ('DEPT_ASSISTANT', 'Adjoint(e) de département'), ('PROPOSAL_MANAGER', 'Gestionnaire de propositions'), ('ADMIN', 'Administrateur')], max_length=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_project_role',
                'constraints': [models.UniqueConstraint(fields=('user', 'project_id', 'tenant'), name='uq_project_role_user_project_tenant')],
            },
        ),
    ]
