# Generated by Django 6.0.3 on 2026-03-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='sso_only',
            field=models.BooleanField(default=False, help_text='When True, only SSO login is allowed (except ADMIN users).'),
        ),
    ]
