# Generated by Django 6.0.3 on 2026-03-20 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_delegation_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_bus', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'core_business_unit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LaborRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ex: Québec standard, Ontario standard', max_length=255)),
                ('weekly_hours', models.DecimalField(decimal_places=1, default=40.0, max_digits=4)),
                ('daily_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('overtime_threshold_weekly', models.DecimalField(decimal_places=1, default=40.0, max_digits=4)),
                ('overtime_threshold_daily', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('statutory_holidays', models.JSONField(default=list, help_text='List of holiday dates: ["2026-01-01", "2026-07-01", ...]')),
                ('rest_days', models.JSONField(default=list, help_text='Days of week that are rest days: [5, 6] for Sat/Sun')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'core_labor_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PositionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('hourly_cost_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'core_position_profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_entity', models.CharField(help_text='Ex: Provencher Roy Productions, PRAA', max_length=255)),
                ('tps_rate', models.DecimalField(decimal_places=3, default=5.0, max_digits=5)),
                ('tvq_rate', models.DecimalField(decimal_places=3, default=9.975, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'core_tax_configuration',
                'ordering': ['legal_entity'],
            },
        ),
    ]
