# Generated by Django 6.0.3 on 2026-03-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_bu_position_tax_labor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconfiguration',
            name='legal_entity',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TaxScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ex: Québec TPS+TVQ, Ontario TVH', max_length=255)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text='Schéma par défaut pour les nouveaux clients')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'core_tax_scheme',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('TPS', 'TPS (Taxe fédérale)'), ('TVQ', 'TVQ (Taxe Québec)'), ('TVH', 'TVH (Taxe harmonisée)'), ('GST', 'GST (Federal goods & services)'), ('PST', 'PST (Provincial sales tax)'), ('HST', 'HST (Harmonized sales tax)'), ('OTHER', 'Autre taxe')], max_length=10)),
                ('label', models.CharField(blank=True, default='', help_text='Libellé personnalisé si nécessaire', max_length=100)),
                ('rate', models.DecimalField(decimal_places=3, help_text='Taux en pourcentage (ex: 9.975)', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.taxscheme')),
            ],
            options={
                'db_table': 'core_tax_rate',
                'ordering': ['scheme', 'tax_type'],
            },
        ),
    ]
