# Generated by Django 6.0.3 on 2026-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_tax_scheme_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('PM', 'Project Manager'), ('PROJECT_DIRECTOR', 'Associé en charge'), ('BU_DIRECTOR', "Directeur d'unité"), ('FINANCE', 'Finance'), ('PAIE', 'Paie'), ('DEPT_ASSISTANT', 'Adjoint(e) de département'), ('PROPOSAL_MANAGER', 'Gestionnaire de propositions'), ('ADMIN', 'Administrateur')], max_length=30),
        ),
    ]
