# Generated by Django 6.0.3 on 2026-04-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_public_consortium_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenantassociation',
            name='contract_hours_override',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Override weekly contract hours (e.g., 37.5 for part-time)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='usertenantassociation',
            name='labor_rule',
            field=models.ForeignKey(blank=True, help_text='Labor rule defining contract hours, overtime thresholds', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.laborrule'),
        ),
    ]
