# Generated by Django 6.0.3 on 2026-04-07 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseline',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='expense_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
