# Generated by Django 6.0.3 on 2026-04-05 13:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_add_tax_scheme_model'),
        ('core', '0008_project_public_consortium_services'),
        ('suppliers', '0003_add_neq_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consortium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('pr_role', models.CharField(choices=[('MANDATAIRE', 'Mandataire (responsable)'), ('PARTENAIRE', 'Partenaire')], default='MANDATAIRE', help_text='Role of Provencher Roy in this consortium', max_length=20)),
                ('contract_reference', models.CharField(blank=True, default='', help_text='External contract or agreement reference number', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(help_text="Donneur d'ouvrage — the end client", on_delete=django.db.models.deletion.PROTECT, related_name='consortiums', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'consortiums_consortium',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConsortium',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('pr_role', models.CharField(choices=[('MANDATAIRE', 'Mandataire (responsable)'), ('PARTENAIRE', 'Partenaire')], default='MANDATAIRE', help_text='Role of Provencher Roy in this consortium', max_length=20)),
                ('contract_reference', models.CharField(blank=True, default='', help_text='External contract or agreement reference number', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, help_text="Donneur d'ouvrage — the end client", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tenant')),
            ],
            options={
                'verbose_name': 'historical consortium',
                'verbose_name_plural': 'historical consortiums',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ConsortiumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pr', models.BooleanField(default=False, help_text='True if this member row represents Provencher Roy')),
                ('name_override', models.CharField(blank=True, default='', help_text='Display name override (used when is_pr=True or for custom labels)', max_length=255)),
                ('coefficient', models.DecimalField(decimal_places=2, default=0, help_text='Participation percentage (all members must sum to 100)', max_digits=5)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('specialty', models.CharField(blank=True, default='', help_text='Firm specialty in this consortium (e.g., structure, MEP)', max_length=255)),
                ('consortium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='consortiums.consortium')),
                ('organization', models.ForeignKey(blank=True, help_text='External organization (null = Provencher Roy itself)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consortium_memberships', to='suppliers.externalorganization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'consortiums_member',
                'ordering': ['-is_pr', '-coefficient'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('consortium', 'organization'), name='uq_consortium_member_org')],
            },
        ),
    ]
