# Generated by Django 6.0.3 on 2026-04-06 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoiceline_task_fk'),
        ('core', '0009_user_labor_rule_contract_hours'),
        ('projects', '0006_project_consortium_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='tax_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tax scheme used for this invoice', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.taxscheme'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='taxes_detail',
            field=models.JSONField(blank=True, default=list, help_text='Calculated taxes: [{"type": "TPS", "label": "TPS", "rate": 5.0, "amount": 125.00}, ...]'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='total_with_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_scheme',
            field=models.ForeignKey(blank=True, help_text='Tax scheme used for this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.taxscheme'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxes_detail',
            field=models.JSONField(blank=True, default=list, help_text='Calculated taxes: [{"type": "TPS", "label": "TPS", "rate": 5.0, "amount": 125.00}, ...]'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_with_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='financial_phase',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED — use task instead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.financialphase'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('FORFAIT', 'Forfait'), ('HORAIRE', 'Horaire'), ('ST', 'Sous-traitant'), ('DEPENSE', 'Dépense'), ('AUTRE', 'Autre (libre)')], default='FORFAIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Task (WBS) for this invoice line — replaces financial_phase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='projects.task'),
        ),
    ]
