# Generated by Django 6.0.3 on 2026-04-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_invoice_tax_scheme"),
        ("projects", "0009_phase_amendment_task_amendment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoice",
            name="amendment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Required when invoice_mode=AMENDMENT_DEDICATED. Must remain NULL when invoice_mode=MERGED.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projects.amendment",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="invoice_mode",
            field=models.CharField(
                choices=[("MERGED", "Fusionné"), ("AMENDMENT_DEDICATED", "Dédié avenant")],
                default="MERGED",
                help_text="MERGED: main + amendment lines combined. AMENDMENT_DEDICATED: only lines of one amendment.",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="amendment",
            field=models.ForeignKey(
                blank=True,
                help_text="Required when invoice_mode=AMENDMENT_DEDICATED. Must remain NULL when invoice_mode=MERGED.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="projects.amendment",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_mode",
            field=models.CharField(
                choices=[("MERGED", "Fusionné"), ("AMENDMENT_DEDICATED", "Dédié avenant")],
                default="MERGED",
                help_text="MERGED: main + amendment lines combined. AMENDMENT_DEDICATED: only lines of one amendment.",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="amendment",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this line belongs to an amendment (avenant) rather than the main project scope.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_lines",
                to="projects.amendment",
            ),
        ),
    ]
