# Generated by Django 6.0.3 on 2026-03-18 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_projectrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('neq', models.CharField(blank=True, db_index=True, default='', help_text="Numéro d'entreprise du Québec", max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(default='Québec', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('banking_info', models.JSONField(blank=True, default=dict)),
                ('type_tags', models.JSONField(blank=True, default=list, help_text='Role tags: ["st", "partner", "competitor"]')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'suppliers_external_org',
                'ordering': ['name'],
            },
        ),
    ]
