# Generated by Django 6.0.3 on 2026-03-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_delegation_model'),
        ('suppliers', '0002_historicalstholdback_historicalstinvoice_stholdback_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='externalorganization',
            constraint=models.UniqueConstraint(condition=models.Q(('neq__gt', '')), fields=('neq', 'tenant'), name='uq_supplier_neq_tenant'),
        ),
    ]
