# Generated by Django 6.0.3 on 2026-03-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0007_add_tax_scheme_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tax_scheme',
            field=models.ForeignKey(blank=True, help_text='Schéma fiscal applicable (TPS+TVQ, TVH, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.taxscheme'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='tax_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Schéma fiscal applicable (TPS+TVQ, TVH, etc.)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.taxscheme'),
        ),
    ]
