# Generated by Django 6.0.3 on 2026-04-05 22:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_user_labor_rule_contract_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, default='', max_length=100)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_medical_cert', models.BooleanField(default=False, help_text='Requires medical certificate if absence > threshold days')),
                ('medical_cert_threshold_days', models.PositiveIntegerField(default=3, help_text='Number of consecutive days before medical cert required')),
                ('max_days_per_year', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum days per year (null = unlimited)', max_digits=5, null=True)),
                ('accrual_rate_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Days accrued per month (0 = no accrual, allocated upfront)', max_digits=5)),
                ('can_carry_over', models.BooleanField(default=False, help_text='Can unused days carry over to next year')),
                ('carry_over_max_days', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum days that can carry over', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'leaves_type',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8, help_text='Hours per day (7.5 or 8 typically)', max_digits=4)),
                ('total_days', models.DecimalField(decimal_places=2, help_text='Total leave days requested (can be 0.5 for half-day)', max_digits=5)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('medical_cert_uploaded', models.BooleanField(default=False)),
                ('time_entries_created', models.BooleanField(default=False, help_text='True if TimeEntry records were auto-created on approval')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leaves.leavetype')),
            ],
            options={
                'db_table': 'leaves_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('accrued', models.DecimalField(decimal_places=2, default=0, help_text='Total days accrued for the year', max_digits=6)),
                ('used', models.DecimalField(decimal_places=2, default=0, help_text='Total days used (approved leaves)', max_digits=6)),
                ('carried_over', models.DecimalField(decimal_places=2, default=0, help_text='Days carried over from previous year', max_digits=6)),
                ('manual_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Manual adjustment by HR (positive or negative)', max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_banks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='leaves.leavetype')),
            ],
            options={
                'db_table': 'leaves_bank',
                'ordering': ['-year', 'leave_type__order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLeaveRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8, help_text='Hours per day (7.5 or 8 typically)', max_digits=4)),
                ('total_days', models.DecimalField(decimal_places=2, help_text='Total leave days requested (can be 0.5 for half-day)', max_digits=5)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('medical_cert_uploaded', models.BooleanField(default=False)),
                ('time_entries_created', models.BooleanField(default=False, help_text='True if TimeEntry records were auto-created on approval')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tenant')),
                ('leave_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'historical leave request',
                'verbose_name_plural': 'historical leave requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('labor_rule', models.ForeignKey(blank=True, help_text='Jurisdiction this holiday applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.laborrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'leaves_public_holiday',
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('code', 'tenant'), name='uq_leave_type_code_tenant'),
        ),
        migrations.AddConstraint(
            model_name='leavebank',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year', 'tenant'), name='uq_leave_bank_employee_type_year'),
        ),
        migrations.AddConstraint(
            model_name='publicholiday',
            constraint=models.UniqueConstraint(fields=('date', 'tenant'), name='uq_public_holiday_date_tenant'),
        ),
    ]
