# Generated by Django 6.0.3 on 2026-06-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_team'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publicholiday',
            name='uq_public_holiday_date_tenant',
        ),
        migrations.AddConstraint(
            model_name='publicholiday',
            constraint=models.UniqueConstraint(condition=models.Q(('labor_rule__isnull', False)), fields=('date', 'tenant', 'labor_rule'), name='uq_public_holiday_date_tenant_rule'),
        ),
        migrations.AddConstraint(
            model_name='publicholiday',
            constraint=models.UniqueConstraint(condition=models.Q(('labor_rule__isnull', True)), fields=('date', 'tenant'), name='uq_public_holiday_date_tenant_global'),
        ),
    ]
