# Generated by Django 6.0.3 on 2026-06-06 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sidebar_config'),
        ('projects', '0013_standard_phase'),
        ('time_entries', '0006_timeentry_task_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltimeentry',
            name='phase',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='DEPRECATED — use task instead', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.phase'),
        ),
        migrations.AlterField(
            model_name='historicaltimeentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('PM_APPROVED', 'Approuvé PM'), ('FINANCE_APPROVED', 'Approuvé Finance'), ('PAIE_VALIDATED', 'Validé Paie'), ('LOCKED', 'Verrouillé')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltimeentry',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Task (WBS) for this time entry — replaces phase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='periodfreeze',
            name='frozen_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_freezes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='periodfreeze',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED — use task instead', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.phase'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('PM_APPROVED', 'Approuvé PM'), ('FINANCE_APPROVED', 'Approuvé Finance'), ('PAIE_VALIDATED', 'Validé Paie'), ('LOCKED', 'Verrouillé')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Task (WBS) for this time entry — replaces phase', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.task'),
        ),
    ]
