# Generated by Django 6.0.3 on 2026-06-06 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_historicalinvoice_amendment_and_more'),
        ('core', '0010_sidebar_config'),
        ('projects', '0013_standard_phase'),
        ('time_entries', '0007_alter_historicaltimeentry_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeentry',
            name='uq_time_entry_employee_project_phase_date',
        ),
        migrations.AddConstraint(
            model_name='timeentry',
            constraint=models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('employee', 'project', 'task', 'date'), name='uq_time_entry_employee_project_task_date'),
        ),
    ]
