# Generated by Django 6.0.3 on 2026-06-09 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_team'),
        ('projects', '0016_support_services_to_phases'),
        ('time_entries', '0008_timeentry_task_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entry_blocks', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entry_blocks', to='projects.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entry_blocks', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entry_blocks', to='projects.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'time_entries_block',
                'ordering': ['employee_id', 'phase_id', 'task_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('phase__isnull', False), ('task__isnull', True)), models.Q(('phase__isnull', True), ('task__isnull', False)), _connector='OR'), name='time_entry_block_phase_xor_task'), models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('employee', 'task'), name='uq_time_entry_block_employee_task'), models.UniqueConstraint(condition=models.Q(('phase__isnull', False)), fields=('employee', 'phase'), name='uq_time_entry_block_employee_phase')],
            },
        ),
    ]
