# Generated by Django 6.0.3 on 2026-06-09 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_team'),
        ('projects', '0016_support_services_to_phases'),
        ('time_entries', '0009_timeentryblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeentryblock',
            name='time_entry_block_phase_xor_task',
        ),
        migrations.AddConstraint(
            model_name='timeentryblock',
            constraint=models.CheckConstraint(condition=models.Q(('phase__isnull', False), ('task__isnull', False), _negated=True), name='time_entry_block_phase_xor_task'),
        ),
        migrations.AddConstraint(
            model_name='timeentryblock',
            constraint=models.UniqueConstraint(condition=models.Q(('phase__isnull', True), ('task__isnull', True)), fields=('employee', 'project'), name='uq_time_entry_block_employee_project'),
        ),
    ]
