# Generated by Django 6.0.3 on 2026-04-05 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_user_labor_rule_contract_hours'),
        ('projects', '0006_project_consortium_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('UPCOMING', 'À venir'), ('ACHIEVED', 'Atteint'), ('OVERDUE', 'En retard')], default='UPCOMING', max_length=20)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for visual display', max_length=7)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'planning_milestone',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=40, help_text='Planned hours per week on this allocation (min 0.5)', max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_allocations', to='projects.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_allocations', to='projects.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'planning_allocation',
                'ordering': ['start_date', 'employee__username'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('contractual_hours', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('capacity_hours', models.DecimalField(decimal_places=1, default=8, help_text='Available hours after absence deductions', max_digits=4)),
                ('is_working_day', models.BooleanField(default=True)),
                ('leave_type', models.CharField(blank=True, default='', help_text='If absent: leave type code (VACANCES, MALADIE, etc.)', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'planning_availability',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date', 'tenant'), name='uq_availability_employee_date')],
            },
        ),
    ]
