# Generated by Django 6.0.3 on 2026-04-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_labor_rule_contract_hours'),
        ('planning', '0001_initial'),
        ('projects', '0006_project_consortium_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start')], default='FS', max_length=2)),
                ('lag_days', models.IntegerField(default=0, help_text='Delay in days (can be negative)')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='projects.phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_dependencies', to='projects.project')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='projects.phase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'planning_phase_dependency',
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor'), name='uq_phase_dependency')],
            },
        ),
    ]
