# Generated by Django 6.0.3 on 2026-04-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sidebar_config'),
        ('planning', '0002_phase_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceallocation',
            name='distribution_mode',
            field=models.CharField(choices=[('uniform', 'Uniforme'), ('standard', 'Standard'), ('manual', 'Manuelle')], default='uniform', max_length=10),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='time_breakdown',
            field=models.JSONField(blank=True, help_text='For manual/standard modes: {"2026-W18": 20, ...} (week) or {"2026-05": 80, ...} (month)', null=True),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='time_unit',
            field=models.CharField(choices=[('week', 'Semaine'), ('month', 'Mois')], default='week', max_length=10),
        ),
        migrations.CreateModel(
            name='PlanningStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('phase_code', models.CharField(db_index=True, help_text='Matches projects.Phase.code (e.g., ESQUISSE, APS, DD, CHANTIER)', max_length=50)),
                ('time_unit', models.CharField(choices=[('week', 'Semaine'), ('month', 'Mois')], default='week', max_length=10)),
                ('curve', models.JSONField(default=list, help_text='Normalized relative distribution: [0.4, 0.3, 0.2, 0.1] — sum must equal 1.0 ± 0.01')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'planning_standard',
                'ordering': ['phase_code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_allocations', to='planning.planningstandard'),
        ),
    ]
