# Generated by Django 6.0.3 on 2026-04-22 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sidebar_config'),
        ('planning', '0004_migrate_employee_assignments'),
        ('projects', '0009_phase_amendment_task_amendment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceallocation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VirtualResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Libellé du profil (ex. 'Architecte senior', 'Dessinateur junior').", max_length=255)),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Taux horaire par défaut (CA).', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_resources', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'planning_virtual_resource',
                'ordering': ['project_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='virtual_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='planning.virtualresource'),
        ),
        migrations.AddConstraint(
            model_name='virtualresource',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uq_virtual_resource_project_name'),
        ),
    ]
