# Generated by Django 6.0.3 on 2026-04-24 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_virtual_resource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualresource',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualresource',
            name='replaced_by',
            field=models.ForeignKey(blank=True, help_text='Employé réel qui a remplacé ce profil virtuel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_resources_taken_over', to=settings.AUTH_USER_MODEL),
        ),
    ]
